/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidaturesRouteImport } from './routes/candidatures'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as EntreprisesIndexRouteImport } from './routes/entreprises.index'
import { Route as EntreprisesCompanyRouteImport } from './routes/entreprises.$company'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturesRoute = CandidaturesRouteImport.update({
  id: '/candidatures',
  path: '/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesIndexRoute = EntreprisesIndexRouteImport.update({
  id: '/entreprises/',
  path: '/entreprises/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesCompanyRoute = EntreprisesCompanyRouteImport.update({
  id: '/entreprises/$company',
  path: '/entreprises/$company',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/emails': typeof EmailsRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/emails': typeof EmailsRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts': typeof ContactsIndexRoute
  '/entreprises': typeof EntreprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/emails': typeof EmailsRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidatures'
    | '/emails'
    | '/kanban'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts/'
    | '/entreprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidatures'
    | '/emails'
    | '/kanban'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts'
    | '/entreprises'
  id:
    | '__root__'
    | '/'
    | '/candidatures'
    | '/emails'
    | '/kanban'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts/'
    | '/entreprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidaturesRoute: typeof CandidaturesRoute
  EmailsRoute: typeof EmailsRoute
  KanbanRoute: typeof KanbanRoute
  ParametresRoute: typeof ParametresRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  EntreprisesCompanyRoute: typeof EntreprisesCompanyRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  EntreprisesIndexRoute: typeof EntreprisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatures': {
      id: '/candidatures'
      path: '/candidatures'
      fullPath: '/candidatures'
      preLoaderRoute: typeof CandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/': {
      id: '/entreprises/'
      path: '/entreprises'
      fullPath: '/entreprises/'
      preLoaderRoute: typeof EntreprisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/$company': {
      id: '/entreprises/$company'
      path: '/entreprises/$company'
      fullPath: '/entreprises/$company'
      preLoaderRoute: typeof EntreprisesCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidaturesRoute: CandidaturesRoute,
  EmailsRoute: EmailsRoute,
  KanbanRoute: KanbanRoute,
  ParametresRoute: ParametresRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  EntreprisesCompanyRoute: EntreprisesCompanyRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  EntreprisesIndexRoute: EntreprisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
