/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidaturesRouteImport } from './routes/candidatures'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ParametresRouteImport } from './routes/parametres'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturesRoute = CandidaturesRouteImport.update({
  id: '/candidatures',
  path: '/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidatures': typeof CandidaturesRoute
  '/kanban': typeof KanbanRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidatures' | '/kanban' | '/parametres'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidatures' | '/kanban' | '/parametres'
  id: '__root__' | '/' | '/candidatures' | '/kanban' | '/parametres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidaturesRoute: typeof CandidaturesRoute
  KanbanRoute: typeof KanbanRoute
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatures': {
      id: '/candidatures'
      path: '/candidatures'
      fullPath: '/candidatures'
      preLoaderRoute: typeof CandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidaturesRoute: CandidaturesRoute,
  KanbanRoute: KanbanRoute,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
