/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CandidaturesRouteImport } from './routes/candidatures'
import { Route as DataQualityRouteImport } from './routes/data-quality'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as MonCvRouteImport } from './routes/mon-cv'
import { Route as OffresRouteImport } from './routes/offres'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as EntreprisesIndexRouteImport } from './routes/entreprises.index'
import { Route as EntreprisesCompanyRouteImport } from './routes/entreprises.$company'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturesRoute = CandidaturesRouteImport.update({
  id: '/candidatures',
  path: '/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const DataQualityRoute = DataQualityRouteImport.update({
  id: '/data-quality',
  path: '/data-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCvRoute = MonCvRouteImport.update({
  id: '/mon-cv',
  path: '/mon-cv',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresRoute = OffresRouteImport.update({
  id: '/offres',
  path: '/offres',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesIndexRoute = EntreprisesIndexRouteImport.update({
  id: '/entreprises/',
  path: '/entreprises/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntreprisesCompanyRoute = EntreprisesCompanyRouteImport.update({
  id: '/entreprises/$company',
  path: '/entreprises/$company',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/candidatures': typeof CandidaturesRoute
  '/data-quality': typeof DataQualityRoute
  '/emails': typeof EmailsRoute
  '/intelligence': typeof IntelligenceRoute
  '/kanban': typeof KanbanRoute
  '/mon-cv': typeof MonCvRoute
  '/offres': typeof OffresRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/candidatures': typeof CandidaturesRoute
  '/data-quality': typeof DataQualityRoute
  '/emails': typeof EmailsRoute
  '/intelligence': typeof IntelligenceRoute
  '/kanban': typeof KanbanRoute
  '/mon-cv': typeof MonCvRoute
  '/offres': typeof OffresRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts': typeof ContactsIndexRoute
  '/entreprises': typeof EntreprisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/candidatures': typeof CandidaturesRoute
  '/data-quality': typeof DataQualityRoute
  '/emails': typeof EmailsRoute
  '/intelligence': typeof IntelligenceRoute
  '/kanban': typeof KanbanRoute
  '/mon-cv': typeof MonCvRoute
  '/offres': typeof OffresRoute
  '/parametres': typeof ParametresRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/entreprises/$company': typeof EntreprisesCompanyRoute
  '/contacts/': typeof ContactsIndexRoute
  '/entreprises/': typeof EntreprisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/analytics'
    | '/candidatures'
    | '/data-quality'
    | '/emails'
    | '/intelligence'
    | '/kanban'
    | '/mon-cv'
    | '/offres'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts/'
    | '/entreprises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/analytics'
    | '/candidatures'
    | '/data-quality'
    | '/emails'
    | '/intelligence'
    | '/kanban'
    | '/mon-cv'
    | '/offres'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts'
    | '/entreprises'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/analytics'
    | '/candidatures'
    | '/data-quality'
    | '/emails'
    | '/intelligence'
    | '/kanban'
    | '/mon-cv'
    | '/offres'
    | '/parametres'
    | '/contacts/$contactId'
    | '/entreprises/$company'
    | '/contacts/'
    | '/entreprises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CandidaturesRoute: typeof CandidaturesRoute
  DataQualityRoute: typeof DataQualityRoute
  EmailsRoute: typeof EmailsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  KanbanRoute: typeof KanbanRoute
  MonCvRoute: typeof MonCvRoute
  OffresRoute: typeof OffresRoute
  ParametresRoute: typeof ParametresRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  EntreprisesCompanyRoute: typeof EntreprisesCompanyRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  EntreprisesIndexRoute: typeof EntreprisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatures': {
      id: '/candidatures'
      path: '/candidatures'
      fullPath: '/candidatures'
      preLoaderRoute: typeof CandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-quality': {
      id: '/data-quality'
      path: '/data-quality'
      fullPath: '/data-quality'
      preLoaderRoute: typeof DataQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-cv': {
      id: '/mon-cv'
      path: '/mon-cv'
      fullPath: '/mon-cv'
      preLoaderRoute: typeof MonCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres': {
      id: '/offres'
      path: '/offres'
      fullPath: '/offres'
      preLoaderRoute: typeof OffresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/': {
      id: '/entreprises/'
      path: '/entreprises'
      fullPath: '/entreprises/'
      preLoaderRoute: typeof EntreprisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entreprises/$company': {
      id: '/entreprises/$company'
      path: '/entreprises/$company'
      fullPath: '/entreprises/$company'
      preLoaderRoute: typeof EntreprisesCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CandidaturesRoute: CandidaturesRoute,
  DataQualityRoute: DataQualityRoute,
  EmailsRoute: EmailsRoute,
  IntelligenceRoute: IntelligenceRoute,
  KanbanRoute: KanbanRoute,
  MonCvRoute: MonCvRoute,
  OffresRoute: OffresRoute,
  ParametresRoute: ParametresRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  EntreprisesCompanyRoute: EntreprisesCompanyRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  EntreprisesIndexRoute: EntreprisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
